title: PRC2 with HX and EM
date: 2019-07-10T12:10:31.1913934-06:00
states: 1
sampling_frame: 200
output_dir: ./imp_model
data_directory: ../
topology_file: Topology.txt
target_gmm_file: gmm_file_ouput.txt
cores: 16 
crosslinkdb:
- refid: PRC2_DSS_BS3_2020_vLoose.csv
- refid: PRC2_DSS_BS3_2020_loose.csv
- refid: PRC2_DSS_BS3_2020_mod.csv
- refid: PRC2_DSS_BS3_2020_tight.csv
- refid: PRC2_DSS_BS3_2020_vTight.csv
xl_groupB:
- refid: PRC2_DSS_BS3_2020_vLoose.csv
  length: 30.0
  slope: 0.01
  resolution: 1.0
  sigma_kappa: 1.6
  sigma_theta: 2.0
  sigma_init: 12
  label: PRC2_DSS_BS3_2020_vLoose
  weight: 1.0
  crosslink_distance: 20.0
- refid: PRC2_DSS_BS3_2020_loose.csv
  length: 30.0
  slope: 0.01
  resolution: 1.0
  sigma_kappa: 1.45
  sigma_theta: 2.0
  sigma_init: 9
  label: PRC2_DSS_BS3_2020_loose
  weight: 1.0
  crosslink_distance: 10.0
- refid: PRC2_DSS_BS3_2020_mod.csv
  length: 30.0
  slope: 0.01
  resolution: 1.0
  sigma_kappa: 1.3
  sigma_theta: 2.0
  sigma_init: 6
  label: PRC2_DSS_BS3_2020_mod
  weight: 1.0
  crosslink_distance: 30.0
- refid: PRC2_DSS_BS3_2020_tight.csv
  length: 30.0
  slope: 0.01
  resolution: 1.0
  sigma_kappa: 1.15
  sigma_theta: 2.0
  sigma_init: 3
  label: PRC2_DSS_BS3_2020_tight
  weight: 1.0
  crosslink_distance: 10.0
- refid: PRC2_DSS_BS3_2020_vTight.csv
  length: 30.0
  slope: -1
  resolution: 1.0
  sigma_kappa: 1.0
  sigma_theta: 2.0
  sigma_init: 1
  label: PRC2_DSS_BS3_2020_vTight
  weight: 1.0
  crosslink_distance: 20.0
xl_dbB:
- refid: PRC2_DSS_BS3_2020_vLoose.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_DSS_BS3_2020_loose.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_DSS_BS3_2020_mod.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_DSS_BS3_2020_tight.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_DSS_BS3_2020_vTight.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
degree_of_freedom:
  max_rb_trans: 4.0
  max_rb_rot: 0.3
  max_bead_trans: 4.0
  max_srb_trans: 4.0
  max_srb_rot: 0.3

