title: PRC2 with HX and EM
date: 2019-07-10T12:10:31.1913934-06:00
states: 1
sampling_frame: 200O0
output_dir: ./imp_model
data_directory: ../
topology_file: Topology.txt
target_gmm_file: gmm_file_ouput.txt
cores: 24 
crosslinkdb:
- refid: PRC2_DSS_unprotected.csv
- refid: PRC2_DSS_standard.csv
- refid: PRC2_DSS_protected.csv
- refid: PRC2_BS3_standard.csv
- refid: PRC2_BS3_unprotected.csv
- refid: PRC2_BS3_protected.csv
xl_groupA:
- refid: PRC2_DSS_unprotected.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: PRC2_DSS_unprotected
  weight: 1.0
  crosslink_distance: 20.0
- refid: PRC2_DSS_standard.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: PRC2_DSS_standard
  weight: 1.0
  crosslink_distance: 10.0
- refid: PRC2_DSS_protected.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: PRC2_DSS_protected
  weight: 1.0
  crosslink_distance: 30.0
- refid: PRC2_BS3_standard.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: PRC2_BS3_standard
  weight: 1.0
  crosslink_distance: 10.0
- refid: PRC2_BS3_unprotected.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: PRC2_BS3_unprotected
  weight: 1.0
  crosslink_distance: 20.0
- refid: PRC2_BS3_protected.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: PRC2_BS3_protected
  weight: 1.0
  crosslink_distance: 30.0
xl_dbA:
- refid: PRC2_DSS_unprotected.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_DSS_standard.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_DSS_protected.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_BS3_standard.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_BS3_unprotected.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_BS3_protected.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
degree_of_freedom:
  max_rb_trans: 4.0
  max_rb_rot: 0.3
  max_bead_trans: 4.0
  max_srb_trans: 4.0
  max_srb_rot: 0.3

